/* THIS IS ONLY FOR LOCAL DEVELOPMENT PURPOSES */
/* THIS IS ONLY FOR LOCAL DEVELOPMENT PURPOSES */
/* THIS IS ONLY FOR LOCAL DEVELOPMENT PURPOSES */
/* THIS IS ONLY FOR LOCAL DEVELOPMENT PURPOSES */
/* THIS IS ONLY FOR LOCAL DEVELOPMENT PURPOSES */
/* THIS IS ONLY FOR LOCAL DEVELOPMENT PURPOSES */
/* THIS IS ONLY FOR LOCAL DEVELOPMENT PURPOSES */
/* THIS IS ONLY FOR LOCAL DEVELOPMENT PURPOSES */

create user users with password 'postgres_password';
create user jobs with password 'postgres_password';

create database users;
create database jobs;

GRANT ALL PRIVILEGES ON DATABASE jobs TO jobs;
GRANT ALL PRIVILEGES ON DATABASE users TO users;

\connect users
GRANT ALL PRIVILEGES ON SCHEMA public TO users;
GRANT USAGE, CREATE ON SCHEMA public TO users;
\connect jobs
GRANT ALL PRIVILEGES ON SCHEMA public TO jobs;
GRANT USAGE, CREATE ON SCHEMA public TO jobs;